name: Job que imprime en la consola 

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC, '00 0 * * FRI' todos los viernes.
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_earnings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run command in the vm
        run: |
          echo "Imorimir tabla de datos"
          ls -lhrt
